services:
  backend:
    environment:
      - DJANGO_SETTINGS_MODULE=calendar_app.settings
    build:
      context: ./backend
    container_name: django_backend
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 &&
             python manage.py migrate"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/db  # New volume for SQLite database
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  sqlite_data: